name: Cypress Test
on: [push]
jobs:
   cypress-run:
     runs-on: ubnutu-latest
     steps:
       - name: Checkout
         uses: action/checkout@v2.3.4
       - name: Cypress.io
         uses: cypress-io/github-action@2.9.7
         with:
          start: npm start
